# release.yml
name: Release
on:
  push:
    tags: ["v*"]
jobs:
  release:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'
          cache: true
      - uses: goreleaser/goreleaser-action@v5
        with:
          # ↓ 'latest' の代わりに具体的な v2 バージョンを指定 (例: v2.0.1)
          version: v2.0.1
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}