name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # これがないとリリースを作成できない
    steps:
      # チェックアウト
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Changelog を正しく動作させるために必要

      # Go をセットアップ
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'
          cache: true

      # リリース
      - uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}